Repository DDWU-UMC/BE, pull requests merged in 2025-02, with the labels that each got.

#3 Feat: 운영진 리스트 조회 API 구현
  src/main/java/com/umc/site/domain/club_admin/controller/ClubAdminController.java
  src/main/java/com/umc/site/domain/club_admin/converter/ClubAdminConverter.java
  src/main/java/com/umc/site/domain/club_admin/dto/ClubAdminResponseDTO.java
  src/main/java/com/umc/site/domain/club_admin/entity/ClubAdmin.java
  src/main/java/com/umc/site/domain/club_admin/enums/Role.java
  src/main/java/com/umc/site/domain/club_admin/repository/ClubAdminRepository.java
  src/main/java/com/umc/site/domain/club_admin/service/ClubAdminQueryService.java
  src/main/java/com/umc/site/domain/club_admin/service/ClubAdminQueryServiceImpl.java
  src/main/java/com/umc/site/domain/image/converter/ImageConverter.java
  src/main/java/com/umc/site/domain/image/dto/ImageResponseDTO.java
  src/main/java/com/umc/site/domain/image/entity/Image.java
  src/main/java/com/umc/site/domain/image/repository/ImageRepository.java
  src/main/java/com/umc/site/domain/role_history/converter/RoleHistoryConverter.java
  src/main/java/com/umc/site/domain/role_history/dto/RoleHistoryResponseDTO.java
  src/main/java/com/umc/site/domain/role_history/entity/RoleHistory.java
  src/main/java/com/umc/site/domain/role_history/repository/RoleHistoryRepository.java
  src/main/java/com/umc/site/global/config/SwaggerConfig.java
Labels: :sparkles: feature

#4 FEAT: 기수별 프로젝트 목록 조회 API 구현 #2
  src/main/java/com/umc/site/domain/cohort/entity/Cohort.java
  src/main/java/com/umc/site/domain/cohort/repository/CohortRepository.java
  src/main/java/com/umc/site/domain/feature/entity/Feature.java
  src/main/java/com/umc/site/domain/feature/repository/FeatureRepository.java
  src/main/java/com/umc/site/domain/image/entity/Image.java
  src/main/java/com/umc/site/domain/image/repository/ImageRepository.java
  src/main/java/com/umc/site/domain/project/controller/ProjectController.java
  src/main/java/com/umc/site/domain/project/converter/ProjectConverter.java
  src/main/java/com/umc/site/domain/project/dto/ProjectResponseDTO.java
  src/main/java/com/umc/site/domain/project/entity/Project.java
  src/main/java/com/umc/site/domain/project/enums/ServiceType.java
  src/main/java/com/umc/site/domain/project/repository/ProjectRepository.java
  src/main/java/com/umc/site/domain/project/service/ProjectQueryService.java
  src/main/java/com/umc/site/domain/project/service/ProjectQueryServiceImpl.java
Labels: :sparkles: feature

#7 Feat: 프로젝트 상세 정보 조회 API 구현
  src/main/java/com/umc/site/domain/club_admin/dto/ClubAdminResponseDTO.java
  src/main/java/com/umc/site/domain/club_admin/entity/ClubAdmin.java
  src/main/java/com/umc/site/domain/club_admin/entity/enums/Role.java
  src/main/java/com/umc/site/domain/feature/converter/FeatureConverter.java
  src/main/java/com/umc/site/domain/feature/dto/FeatureResponseDTO.java
  src/main/java/com/umc/site/domain/feature/repository/FeatureRepository.java
  src/main/java/com/umc/site/domain/project/controller/ProjectController.java
  src/main/java/com/umc/site/domain/project/converter/ProjectConverter.java
  src/main/java/com/umc/site/domain/project/dto/ProjectResponseDTO.java
  src/main/java/com/umc/site/domain/project/service/ProjectQueryService.java
  src/main/java/com/umc/site/domain/project/service/ProjectQueryServiceImpl.java
  src/main/java/com/umc/site/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc/site/global/apiPayload/exception/handler/ProjectHandler.java
Labels: :sparkles: feature

#8 Feat: 기수 목록 조회 API 구현
  src/main/java/com/umc/site/domain/cohort/controller/CohortController.java
  src/main/java/com/umc/site/domain/cohort/converter/CohortConverter.java
  src/main/java/com/umc/site/domain/cohort/dto/CohortResponseDTO.java
  src/main/java/com/umc/site/domain/cohort/service/CohortQueryService.java
  src/main/java/com/umc/site/domain/cohort/service/CohortQueryServiceImpl.java
Labels: :sparkles: feature

#10 Feat: n기 다른 프로젝트 보기 목록 조회 API 구현
  src/main/java/com/umc/site/domain/project/controller/ProjectController.java
  src/main/java/com/umc/site/domain/project/converter/ProjectConverter.java
  src/main/java/com/umc/site/domain/project/dto/ProjectResponseDTO.java
  src/main/java/com/umc/site/domain/project/repository/ProjectRepository.java
  src/main/java/com/umc/site/domain/project/service/ProjectQueryService.java
  src/main/java/com/umc/site/domain/project/service/ProjectQueryServiceImpl.java
Labels: :sparkles: feature

#15 Setting: WebConfig, SecurityConfig 설정
  src/main/java/com/umc/site/global/config/SecurityConfig.java
  src/main/java/com/umc/site/global/config/WebConfig.java
Labels: ⚙ Setting

#21 Feat: 프로젝트 기수 생성 API 구현
  src/main/java/com/umc/site/SiteApplication.java
  src/main/java/com/umc/site/domain/cohort/controller/CohortController.java
  src/main/java/com/umc/site/domain/cohort/converter/CohortConverter.java
  src/main/java/com/umc/site/domain/cohort/dto/CohortRequestDTO.java
  src/main/java/com/umc/site/domain/cohort/dto/CohortResponseDTO.java
  src/main/java/com/umc/site/domain/cohort/service/CohortCommandService.java
  src/main/java/com/umc/site/domain/cohort/service/CohortCommandServiceImpl.java
Labels: :sparkles: feature

#22 Feat: 프로젝트 생성 API 구현
  src/main/java/com/umc/site/domain/feature/converter/FeatureConverter.java
  src/main/java/com/umc/site/domain/feature/dto/FeatureRequestDTO.java
  src/main/java/com/umc/site/domain/image/converter/ImageConverter.java
  src/main/java/com/umc/site/domain/image/entity/Image.java
  src/main/java/com/umc/site/domain/image/service/ImageCommandService.java
  src/main/java/com/umc/site/domain/image/service/ImageCommandServiceImpl.java
  src/main/java/com/umc/site/domain/project/controller/ProjectController.java
  src/main/java/com/umc/site/domain/project/converter/ProjectConverter.java
  src/main/java/com/umc/site/domain/project/dto/ProjectRequestDTO.java
  src/main/java/com/umc/site/domain/project/dto/ProjectResponseDTO.java
  src/main/java/com/umc/site/domain/project/service/ProjectCommandService.java
  src/main/java/com/umc/site/domain/project/service/ProjectCommandServiceImpl.java
  src/main/java/com/umc/site/global/apiPayload/code/status/ErrorStatus.java
Labels: :sparkles: feature

#27 Feat: 운영진 생성 API 구현
  src/main/java/com/umc/site/domain/club_admin/controller/ClubAdminController.java
  src/main/java/com/umc/site/domain/club_admin/converter/ClubAdminConverter.java
  src/main/java/com/umc/site/domain/club_admin/dto/ClubAdminRequestDTO.java
  src/main/java/com/umc/site/domain/club_admin/dto/ClubAdminResponseDTO.java
  src/main/java/com/umc/site/domain/club_admin/service/ClubAdminCommandService.java
  src/main/java/com/umc/site/domain/club_admin/service/ClubAdminCommandServiceImpl.java
  src/main/java/com/umc/site/domain/image/converter/ImageConverter.java
  src/main/java/com/umc/site/domain/image/entity/Image.java
  src/main/java/com/umc/site/domain/image/service/ImageCommandService.java
  src/main/java/com/umc/site/domain/image/service/ImageCommandServiceImpl.java
  src/main/java/com/umc/site/domain/part/entity/Part.java
  src/main/java/com/umc/site/domain/part/entity/enums/PartType.java
  src/main/java/com/umc/site/domain/role_history/converter/RoleHistoryConverter.java
  src/main/java/com/umc/site/domain/role_history/dto/RoleHistoryRequestDTO.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#31 Fix: application.yml 제거 오류
  .github/workflows/dev_deploy.yml
Labels: :bug: bug

#32 Feat: 운영진 리스트 조회 API에서 운영진 직책 가져오는 로직 수정
  src/main/java/com/umc/site/domain/club_admin/converter/ClubAdminConverter.java
  src/main/java/com/umc/site/domain/club_admin/dto/ClubAdminResponseDTO.java
  src/main/java/com/umc/site/domain/club_admin/service/ClubAdminQueryServiceImpl.java
Labels: :sparkles: feature

#34 Feat: 프로젝트 기수 수정 API 구현
  src/main/java/com/umc/site/domain/cohort/controller/CohortController.java
  src/main/java/com/umc/site/domain/cohort/converter/CohortConverter.java
  src/main/java/com/umc/site/domain/cohort/dto/CohortRequestDTO.java
  src/main/java/com/umc/site/domain/cohort/dto/CohortResponseDTO.java
  src/main/java/com/umc/site/domain/cohort/entity/Cohort.java
  src/main/java/com/umc/site/domain/cohort/service/CohortCommandService.java
  src/main/java/com/umc/site/domain/cohort/service/CohortCommandServiceImpl.java
  src/main/java/com/umc/site/global/apiPayload/exception/handler/CohortHandler.java
Labels: :sparkles: feature

#37 Setting: 이미지(s3) 설정
  src/main/java/com/umc/site/global/config/AmazonConfig.java
  src/main/java/com/umc/site/global/manager/AmazonS3Manager.java
Labels: ⚙ Setting

#35 Feat: 프로젝트 수정 API 구현
  src/main/java/com/umc/site/domain/feature/repository/FeatureRepository.java
  src/main/java/com/umc/site/domain/image/entity/Image.java
  src/main/java/com/umc/site/domain/image/service/ImageCommandService.java
  src/main/java/com/umc/site/domain/image/service/ImageCommandServiceImpl.java
  src/main/java/com/umc/site/domain/project/controller/ProjectController.java
  src/main/java/com/umc/site/domain/project/converter/ProjectConverter.java
  src/main/java/com/umc/site/domain/project/dto/ProjectRequestDTO.java
  src/main/java/com/umc/site/domain/project/dto/ProjectResponseDTO.java
  src/main/java/com/umc/site/domain/project/entity/Project.java
  src/main/java/com/umc/site/domain/project/service/ProjectCommandService.java
  src/main/java/com/umc/site/domain/project/service/ProjectCommandServiceImpl.java
  src/main/java/com/umc/site/global/manager/AmazonS3Manager.java
Labels: :sparkles: feature

#42 Feat: 프로젝트 상세 조회 응답에 introduction 추가
  src/main/java/com/umc/site/domain/project/converter/ProjectConverter.java
  src/main/java/com/umc/site/domain/project/dto/ProjectResponseDTO.java
  src/main/java/com/umc/site/domain/project/entity/Project.java
Labels: :sparkles: feature

#41 Feat: 모집 중인 파트 조회 API, 커리큘럼 조회 API 구현
  build.gradle
  src/main/java/com/umc/site/domain/curriculum/controller/CurriculumController.java
  src/main/java/com/umc/site/domain/curriculum/converter/CurriculumConverter.java
  src/main/java/com/umc/site/domain/curriculum/dto/CurriculumResponseDTO.java
  src/main/java/com/umc/site/domain/curriculum/entity/Curriculum.java
  src/main/java/com/umc/site/domain/curriculum/repository/CurriculumRepository.java
  src/main/java/com/umc/site/domain/curriculum/service/CurriculumQueryService.java
  src/main/java/com/umc/site/domain/curriculum/service/CurriculumQueryServiceImpl.java
  src/main/java/com/umc/site/domain/part/controller/PartController.java
  src/main/java/com/umc/site/domain/part/converter/PartConverter.java
  src/main/java/com/umc/site/domain/part/dto/PartResponseDTO.java
  src/main/java/com/umc/site/domain/part/entity/Part.java
  src/main/java/com/umc/site/domain/part/entity/enums/PartType.java
  src/main/java/com/umc/site/domain/part/repository/PartRepository.java
  src/main/java/com/umc/site/domain/part/service/PartQueryService.java
  src/main/java/com/umc/site/domain/part/service/PartQueryServiceImpl.java
  src/main/java/com/umc/site/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc/site/global/apiPayload/exception/handler/PartHandler.java
  src/main/java/com/umc/site/global/validation/annotation/ValidPart.java
  src/main/java/com/umc/site/global/validation/validator/PartValidator.java
Labels: :sparkles: feature

#44 Feat: 프로젝트 생성 수정에 introduction 추가
  src/main/java/com/umc/site/domain/project/converter/ProjectConverter.java
  src/main/java/com/umc/site/domain/project/dto/ProjectRequestDTO.java
  src/main/java/com/umc/site/domain/project/entity/Project.java
Labels: :sparkles: feature

#47 Setting: 배포 서버 cors 설정
  src/main/java/com/umc/site/global/config/SecurityConfig.java
  src/main/java/com/umc/site/global/config/WebConfig.java
Labels: ⚙ Setting

#45 Feat: 운영진 수정 API 구현
  src/main/java/com/umc/site/domain/club_admin/controller/ClubAdminController.java
  src/main/java/com/umc/site/domain/club_admin/converter/ClubAdminConverter.java
  src/main/java/com/umc/site/domain/club_admin/dto/ClubAdminRequestDTO.java
  src/main/java/com/umc/site/domain/club_admin/dto/ClubAdminResponseDTO.java
  src/main/java/com/umc/site/domain/club_admin/entity/ClubAdmin.java
  src/main/java/com/umc/site/domain/club_admin/service/ClubAdminCommandService.java
  src/main/java/com/umc/site/domain/club_admin/service/ClubAdminCommandServiceImpl.java
  src/main/java/com/umc/site/domain/club_admin/service/ClubAdminQueryServiceImpl.java
  src/main/java/com/umc/site/domain/image/entity/Image.java
  src/main/java/com/umc/site/domain/image/repository/ImageRepository.java
  src/main/java/com/umc/site/domain/image/service/ImageCommandService.java
  src/main/java/com/umc/site/domain/image/service/ImageCommandServiceImpl.java
  src/main/java/com/umc/site/domain/role_history/dto/RoleHistoryRequestDTO.java
  src/main/java/com/umc/site/domain/role_history/entity/RoleHistory.java
  src/main/java/com/umc/site/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc/site/global/apiPayload/exception/handler/ClubAdminHandler.java
  src/main/java/com/umc/site/global/apiPayload/exception/handler/ImageHandler.java
  src/main/java/com/umc/site/global/apiPayload/exception/handler/RoleHistoryHandler.java
Labels: :sparkles: feature

#49 Feat: Enum 사용 API Endpoint 소문자로 수정
  src/main/java/com/umc/site/domain/curriculum/controller/CurriculumController.java
  src/main/java/com/umc/site/domain/curriculum/service/CurriculumQueryServiceImpl.java
  src/main/java/com/umc/site/domain/part/entity/enums/PartType.java
  src/main/java/com/umc/site/global/apiPayload/code/status/ErrorStatus.java
Labels: :sparkles: feature

#50 Feat : 기수 삭제 API 구현
  src/main/java/com/umc/site/domain/cohort/controller/CohortController.java
  src/main/java/com/umc/site/domain/cohort/service/CohortCommandService.java
  src/main/java/com/umc/site/domain/cohort/service/CohortCommandServiceImpl.java
Labels: :sparkles: feature

#52 Refactor: n기 다른 프로젝트 보기 목록 조회 API 구현
  src/main/java/com/umc/site/domain/project/repository/ProjectRepository.java
Labels: ♻️refactor

#54 Refactor: 프로젝트 상세설정 null 허용
  src/main/java/com/umc/site/domain/project/dto/ProjectRequestDTO.java
  src/main/java/com/umc/site/domain/project/entity/Project.java
Labels: ♻️refactor

#55 Feat: 프로젝트 삭제 API 구현
  src/main/java/com/umc/site/domain/project/controller/ProjectController.java
  src/main/java/com/umc/site/domain/project/service/ProjectCommandService.java
  src/main/java/com/umc/site/domain/project/service/ProjectCommandServiceImpl.java
Labels: :sparkles: feature

#57 Feat: Project 엔티티 description 길이 증가
  src/main/java/com/umc/site/domain/project/entity/Project.java
Labels: :sparkles: feature

#58 Feat: 프론트 링크 cors 설정에 추가
  src/main/java/com/umc/site/global/config/SecurityConfig.java
  src/main/java/com/umc/site/global/config/WebConfig.java
Labels: ⚙ Setting

#60 Feat: 프론트 사이트 추가
  src/main/java/com/umc/site/global/config/SecurityConfig.java
  src/main/java/com/umc/site/global/config/WebConfig.java
Labels: ⚙ Setting

#62 Feat: 프로젝트 타입 추가
  src/main/java/com/umc/site/domain/project/converter/ProjectConverter.java
  src/main/java/com/umc/site/domain/project/dto/ProjectResponseDTO.java
  src/main/java/com/umc/site/domain/project/enums/ServiceType.java
Labels: :sparkles: feature
